### PR TITLE
Fix outdated Security Disclosure Policy references

### PR DESCRIPTION
**Pull request by dkasak**
Removes stale references to Matrix.org's SDP and replace it with Element's.

### CODE REVIEW

**Comment by dkasak** [comment]
Do I need a changelog entry for this?

**Comment by erikjohnston** [comment]
> Do I need a changelog entry for this?

Yeah, its easier to just always mandate them. We have a `.doc` for documentation changes like this.

**Review by anoadragon453 — CHANGES_REQUESTED** [review]
LGTM minus the newsfile entry.

**Review by anoadragon453 — COMMENTED** [review]
Thanks!

**Pull request merged**
