### PR TITLE
Adapt to Twisted 24.10.0rc1

### PR DESCRIPTION
**Pull request by Yushu2606**
### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [x] [Code style](https://element-hq.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

### CODE REVIEW

**Comment by Yushu2606** [comment]
#17878

**Comment by S7evinK** [comment]
Can you incorporate the changes from #17878 in this PR? [CI](https://github.com/element-hq/synapse/actions/runs/11592447192/job/32274779103?pr=17886#step:6:45) is complaining that `_nameEncoder` can not be found (well, Twisted isn't updated yet, so that makes sense)

**Comment by Yushu2606** [comment]
> Can you incorporate the changes from #17878 in this PR? [CI](https://github.com/element-hq/synapse/actions/runs/11592447192/job/32274779103?pr=17886#step:6:45) is complaining that `_nameEncoder` can not be found (well, Twisted isn't updated yet, so that makes sense)

ok, sure

**Comment by devonh** [comment]
These changes have been superceded by this PR https://github.com/element-hq/synapse/pull/17894.
It removes the usage of internal header encoding API completely.

**Pull request closed without merging**
