### PR TITLE
Remove `Generator` in `_quarantine_media_txn()`

### PR DESCRIPTION
**Pull request by realtyem**
when updating the remote_media_cache table

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#changelog).
* [x] [Code style](https://element-hq.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

### CODE REVIEW

**Comment by anoadragon453** [comment]
@realtyem do you have a reference for why providing generators to `txn.executemany` or `txn.execute_batch` may be a bad idea?

**Comment by realtyem** [comment]
> @realtyem do you have a reference for why providing generators to `txn.executemany` or `txn.execute_batch` may be a bad idea?

https://github.com/matrix-org/synapse/issues/15439

Is a lot of the basis. From that, I distill the TLDR as "Generators may cause inadvertent data loss during a db query retry by exhausting an iterable"

**Comment by realtyem** [comment]
The comments at spot seem to be relevant. Although this set of PR's may not necessarily be (part of|used by) this infrastructure, still seems prudent to *not* use generators as a good habit/safety precaution. It may be they end up used in the future, so don't let our tomorrow selves find the foot gun. (And if they do get used in this infrastructure, then is the 'inspection' infrastructure in *this* function working?)

https://github.com/element-hq/synapse/blob/11bc9a1b3ae21bd2041bf7cc4b93dd70a8c3b93e/synapse/storage/database.py#L683-L695

**Comment by realtyem** [comment]
I believe I misunderstood your question, my apologizes.

In and of itself, there is no reason I know of why you can not use a `Generator` to produce the arguments needed for a call to `executemany()`, for either the sqlite3 library or psycopg2.

However, coming shortly in the future is a bit of a rework for a fair chunk of the database interfacing code and some tightening up of the Typing around it would be a really really good idea. I propose a continuation of work done previously(linked in the issue above, but several links deep into it, I believe). It would make the arguments used for `executemany()` and `execute_batch()` need to be a `Sequence` as it's outer container instead of an `Iterable`. There is some thoughts around using a `Collection` instead, but I believe that using a grouping of arguments that enforces 'deterministic order' to be the correct way forward.

Since that is as simple as a `List` or, preferably, a `Tuple`, I believe it is not an especially hard hill to climb.

**Comment by MadLittleMods** [comment]
This seems fine to do given `parameters: Sequence[SQLQueryParameters]` in a type further down the line of `txn.executemany(...)`

https://github.com/element-hq/synapse/blob/3ae80b0de4abeff2bdbbb9d8735057e6b301a670/synapse/storage/types.py#L47-L49

And the goal is to add proper type hints to `txn.executemany(...)`

**Review by MadLittleMods — APPROVED** [review]

**Pull request merged**
