### PR TITLE
register_new_matrix_user: add password-file flag

### PR DESCRIPTION
**Pull request by Mic92**
getpass in python exist on stdin to be a tty, hence we cannot just pipe into register_new_matrix_user. --password-file instead works better and it would also allow the use of stdin if /dev/stdin is passed.

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [ ] Pull request includes a [changelog file](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [ ] [Code style](https://element-hq.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

### CODE REVIEW

**Comment by Mic92** [comment]
I tried running the linters with `nix develop` but ran into issues:

```
Project environment contains an invalid distribution (/tmp/keen-cori-UH6QA5/synapse/.devenv/state/venv/lib/python3.10/site-packages/pip-23.1.2.dist-info). Consider removing it manually or recreate the environment.
Project environment contains an invalid distribution (/tmp/keen-cori-UH6QA5/synapse/.devenv/state/venv/lib/python3.10/site-packages/wheel-0.40.0.dist-info). Consider removing it manually or recreate the environment.
Installing dependencies from lock file

Package operations: 1 install, 0 updates, 21 removals

  • Removing authlib (1.3.0)
  • Removing defusedxml (0.7.1)
  • Removing elementpath (4.1.5)
  • Removing hiredis (2.3.2)
  • Removing jaeger-client (4.8.0)
  • Removing ldap3 (2.9.1)
  • Removing lxml (5.2.2)
  • Removing matrix-synapse-ldap3 (0.3.0)
  • Removing opentracing (2.4.0)
  • Removing psycopg2 (2.9.9)
  • Removing pyicu (2.13.1)
  • Removing pympler (1.0.1)
  • Removing pysaml2 (7.3.1)
  • Removing python-dateutil (2.8.2)
  • Removing pytz (2022.7.1)
  • Removing sentry-sdk (2.3.1)
  • Removing threadloop (1.0.2)
  • Removing thrift (0.16.0)
  • Removing tornado (6.4)
  • Removing txredisapi (1.4.10)
  • Removing xmlschema (2.4.0)
  • Installing ruff (0.3.7): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke build_wheel

  Running `maturin pep517 build-wheel -i /tmp/tmpjmtwgr0s/.venv/bin/python --compatibility off`
  🍹 Building a mixed python/rust project
  🔗 Found bin bindings
  📡 Using build options bindings from pyproject.toml
  warning: /tmp/tmpizqfli4z/ruff-0.3.7/crates/ruff_index/Cargo.toml: unused manifest key `lints` (may be supported in a future version)

  this Cargo does not support nightly features, but if you
  switch to nightly channel you can pass
  `-Zlints` to enable this feature.
  warning: /tmp/tmpizqfli4z/ruff-0.3.7/crates/ruff_notebook/Cargo.toml: unused manifest key `lints` (may be supported in a future version)

  this Cargo does not support nightly features, but if you
  switch to nightly channel you can pass
  `-Zlints` to enable this feature.
  warning: /tmp/tmpizqfli4z/ruff-0.3.7/crates/ruff_python_stdlib/Cargo.toml: unused manifest key `lints` (may be supported in a future version)

  this Cargo does not support nightly features, but if you
  switch to nightly channel you can pass
  `-Zlints` to enable this feature.
  warning: /tmp/tmpizqfli4z/ruff-0.3.7/crates/ruff_cache/Cargo.toml: unused manifest key `lints` (may be supported in a future version)

  this Cargo does not support nightly features, but if you
  switch to nightly channel you can pass
  `-Zlints` to enable this feature.
  warning: /tmp/tmpizqfli4z/ruff-0.3.7/crates/ruff_text_size/Cargo.toml: unused manifest key `lints` (may be supported in a future version)

  this Cargo does not support nightly features, but if you
  switch to nightly channel you can pass
  `-Zlints` to enable this feature.
  warning: /tmp/tmpizqfli4z/ruff-0.3.7/crates/ruff_server/Cargo.toml: unused manifest key `lints` (may be supported in a future version)

  this Cargo does not support nightly features, but if you
  switch to nightly channel you can pass
  `-Zlints` to enable this feature.
  warning: /tmp/tmpizqfli4z/ruff-0.3.7/crates/ruff_python_semantic/Cargo.toml: unused manifest key `lints` (may be supported in a future version)

  this Cargo does not support nightly features, but if you
  switch to nightly channel you can pass
  `-Zlints` to enable this feature.
  warning: /tmp/tmpizqfli4z/ruff-0.3.7/crates/ruff_formatter/Cargo.toml: unused manifest key `lints` (may be supported in a future version)

  this Cargo does not support nightly features, but if you
  switch to nightly channel you can pass
  `-Zlints` to enable this feature.
  warning: /tmp/tmpizqfli4z/ruff-0.3.7/crates/ruff_python_literal/Cargo.toml: unused manifest key `lints` (may be supported in a future version)

  this Cargo does not support nightly features, but if you
  switch to nightly channel you can pass
  `-Zlints` to enable this feature.
  warning: /tmp/tmpizqfli4z/ruff-0.3.7/crates/ruff_source_file/Cargo.toml: unused manifest key `lints` (may be supported in a future version)

  this Cargo does not support nightly features, but if you
  switch to nightly channel you can pass
  `-Zlints` to enable this feature.
  warning: /tmp/tmpizqfli4z/ruff-0.3.7/crates/ruff_python_ast/Cargo.toml: unused manifest key `lints` (may be supported in a future version)

  this Cargo does not support nightly features, but if you
  switch to nightly channel you can pass
  `-Zlints` to enable this feature.
  warning: /tmp/tmpizqfli4z/ruff-0.3.7/crates/ruff_linter/Cargo.toml: unused manifest key `lints` (may be supported in a future version)

  this Cargo does not support nightly features, but if you
  switch to nightly channel you can pass
  `-Zlints` to enable this feature.
  warning: /tmp/tmpizqfli4z/ruff-0.3.7/crates/ruff_macros/Cargo.toml: unused manifest key `lints` (may be supported in a future version)

  this Cargo does not support nightly features, but if you
  switch to nightly channel you can pass
  `-Zlints` to enable this feature.
  warning: /tmp/tmpizqfli4z/ruff-0.3.7/crates/ruff_python_codegen/Cargo.toml: unused manifest key `lints` (may be supported in a future version)

  this Cargo does not support nightly features, but if you
  switch to nightly channel you can pass
  `-Zlints` to enable this feature.
  warning: /tmp/tmpizqfli4z/ruff-0.3.7/crates/ruff_python_formatter/Cargo.toml: unused manifest key `lints` (may be supported in a future version)

  this Cargo does not support nightly features, but if you
  switch to nightly channel you can pass
  `-Zlints` to enable this feature.
  warning: /tmp/tmpizqfli4z/ruff-0.3.7/crates/ruff_workspace/Cargo.toml: unused manifest key `lints` (may be supported in a future version)

  this Cargo does not support nightly features, but if you
  switch to nightly channel you can pass
  `-Zlints` to enable this feature.
  warning: /tmp/tmpizqfli4z/ruff-0.3.7/crates/ruff_python_index/Cargo.toml: unused manifest key `lints` (may be supported in a future version)

  this Cargo does not support nightly features, but if you
  switch to nightly channel you can pass
  `-Zlints` to enable this feature.
  warning: /tmp/tmpizqfli4z/ruff-0.3.7/crates/ruff/Cargo.toml: unused manifest key `lints` (may be supported in a future version)

  this Cargo does not support nightly features, but if you
  switch to nightly channel you can pass
  `-Zlints` to enable this feature.
  warning: /tmp/tmpizqfli4z/ruff-0.3.7/crates/ruff_python_trivia/Cargo.toml: unused manifest key `lints` (may be supported in a future version)

  this Cargo does not support nightly features, but if you
  switch to nightly channel you can pass
  `-Zlints` to enable this feature.
  warning: /tmp/tmpizqfli4z/ruff-0.3.7/crates/ruff_python_parser/Cargo.toml: unused manifest key `lints` (may be supported in a future version)

  this Cargo does not support nightly features, but if you
  switch to nightly channel you can pass
  `-Zlints` to enable this feature.
  error: package `clap v4.5.4` cannot be built because it requires rustc 1.74 or newer, while the currently active rustc version is 1.71.1
  Either upgrade to rustc 1.74 or newer, or use
  cargo update -p clap@4.5.4 --precise ver
  where `ver` is the latest version of `clap` supporting rustc 1.71.1
  💥 maturin failed
    Caused by: Failed to build a native library through cargo
    Caused by: Cargo build finished with "exit status: 101": `env -u CARGO "cargo" "rustc" "--message-format" "json-render-diagnostics" "--manifest-path" "/tmp/tmpizqfli4z/ruff-0.3.7/crates/ruff/Cargo.toml" "--release" "--bin" "ruff" "--" "-C" "link-arg=-s"`
  Error: command ['maturin', 'pep517', 'build-wheel', '-i', '/tmp/tmpjmtwgr0s/.venv/bin/python', '--compatibility', 'off'] returned non-zero exit status 1


  at /nix/store/2l4y0jspbrs0ii3wh038lfffnllx3r0w-python3.10-poetry-1.5.1/lib/python3.10/site-packages/poetry/installation/chef.py:147 in _prepare
      143│
      144│                 error = ChefBuildError("\n\n".join(message_parts))
      145│
      146│             if error is not None:
    → 147│                 raise error from None
      148│
      149│             return path
      150│
      151│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:
```

Hopefully CI also covers this?

**Comment by Mic92** [comment]
Do we need a changelog entry?

**Review by anoadragon453 — CHANGES_REQUESTED** [review]
Thank you for this! This seems useful (especially for NixOS ;) I have a few wording-related comments below.

Apologies, our development flake is well out-of-date. I've been meaning to get to updating it :( Linting is run in CI, yes.

> Do we need a changelog entry?

Yes please, every PR does. Documentation for writing on [is here](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#changelog). This would be a `.feature` newsfile.

**Review by anoadragon453 — APPROVED** [review]
This now LGTM!

> > Thank you for this! This seems useful (especially for NixOS ;) I have a few wording-related comments below.
> 
> This is what I am using it for: [git.clan.lol/clan/clan-core/src/commit/1cbb2d6aa49eaaf1314b2d3254d26e0cc1251be2/clanModules/matrix-synapse/default.nix#L195](https://git.clan.lol/clan/clan-core/src/commit/1cbb2d6aa49eaaf1314b2d3254d26e0cc1251be2/clanModules/matrix-synapse/default.nix#L195)

Ohh, declarative user specification - I like it!

Just a heads up - we prefer contributors not squash commits after review has begun (unlike nixpkgs!) as it makes it harder to see what has changed between reviews. We squash all PR commits before merging so having many commits on the PR itself is not a problem. This PR is small enough that a re-review of the whole changelog is fine though.

**Comment by anoadragon453** [comment]
Oops, this PR needed a debian changelog since we made changes to the `debian/` directory. I've gone ahead and done that in https://github.com/element-hq/synapse/pull/17294/commits/8bf2f410136ca56664296b35866e64401855eb9f.

**Comment by anoadragon453** [comment]
The test failure is a flake and unrelated to this PR. Merging manually.

**Pull request merged**
