### PR TITLE
Handle wildcard type filters properly

### PR DESCRIPTION
**Pull request by thebalaa**
### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [x] Pull request includes a [sign off](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#sign-off)
* [x] [Code style](https://element-hq.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

Signed-off-by: Mo Balaa <mo@fractalnetworks.co>

### CODE REVIEW

**Review by erikjohnston — COMMENTED** [review]
Thanks for this.

Can you expand on why you're suggesting this change? It looks like it might be a bug fix for handling patterns? If so we should add a regression test.

**Comment by thebalaa** [comment]
@erikjohnston do you mean write a test that would have failed previously but now passes?

**Comment by thebalaa** [comment]
@erikjohnston regression test and changelog added

**Comment by thebalaa** [comment]
@erikjohnston this should be good to go, let me know if you have any questions

**Review by erikjohnston — APPROVED** [review]
Thanks!

**Pull request merged**
