### PR TITLE
Fix bug in calculating state for non-gappy syncs

### PR DESCRIPTION
**Pull request by richvdh**
Unfortunately, the optimisation we applied here for non-gappy syncs is not actually valid.

Fixes https://github.com/element-hq/synapse/issues/16941.

~~Based on https://github.com/element-hq/synapse/pull/16930.~~
Requires https://github.com/matrix-org/sytest/pull/1374.

### CODE REVIEW

**Comment by richvdh** [comment]
This doesn't help that much if the client has enabled lazy-loading. S2 is still not sent to the client if it is filtered out via the lazy-loading filter.

Lazy-loading is disabled for a related reason on gappy syncs (see https://github.com/element-hq/element-web/issues/7211). Maybe we also need to disable it for non-gappy syncs?

**Review by erikjohnston — APPROVED** [review]
Ok, I think this is correct. 

It's really quite confusing that `get_state_at` always returns the state at an event, rather than at the token you give it.

Maybe for sliding sync we can actually use the state at a stream token (as I believe we store a mapping from stream ordering to forward extremities), which should make some of this stuff more intuitive??!?!?!?!

**Comment by richvdh** [comment]
> It's really quite confusing that `get_state_at` always returns the state at an event, rather than at the token you give it.
> 
> Maybe for sliding sync we can actually use the state at a stream token (as I believe we store a mapping from stream ordering to forward extremities), which should make some of this stuff more intuitive??!?!?!?!

Yes, though in order to avoid repeatedly doing state res across a given set of extremities, we'd have to store a mapping from stream ordering to state group.

**Comment by richvdh** [comment]
> This doesn't help that much if the client has enabled lazy-loading. S2 is still not sent to the client if it is filtered out via the lazy-loading filter.
> 
> Lazy-loading is disabled for a related reason on gappy syncs (see [element-hq/element-web#7211](https://github.com/element-hq/element-web/issues/7211)). Maybe we also need to disable it for non-gappy syncs?

I had to remember what this was talking about. For the record, I believe it is the scenario I have now spun out to https://github.com/element-hq/synapse/issues/17050.

**Comment by richvdh** [comment]
> It's really quite confusing that get_state_at always returns the state at an event, rather than at the token you give it.
>
> Maybe for sliding sync we can actually use the state at a stream token (as I believe we store a mapping from stream ordering to forward extremities), which should make some of this stuff more intuitive??!?!?!?!

Indeed, though to avoid having to do the same state resolution repeatedly, we'd probably have to also map from a set of forward extremities to a state group?

**Pull request merged**
