### PR TITLE
Support MSC3779: "Owned" state events

### PR DESCRIPTION
**Pull request by AndrewFerr**
See: [MSC3779](https://github.com/matrix-org/matrix-spec-proposals/pull/3779)

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [x] [Code style](https://element-hq.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

### CODE REVIEW

**Comment by erikjohnston** [comment]
Having read the MSC, I have serious reservations on it https://github.com/matrix-org/matrix-spec-proposals/pull/3779#discussion_r1689921789. This doesn't necessarily block us from landing this as an experimental thing, but would block us from enabling it in non-test environments.

**Comment by erikjohnston** [comment]
From discussions elsewhere: we're looking at removing the changes to the required power levels, which is the controversial bit of the MSC. Until then, I'm going to remove this from the review queue.

**Comment by fkwp** [comment]
> From discussions elsewhere: we're looking at removing the changes to the required power levels, which is the controversial bit of the MSC. Until then, I'm going to remove this from the review queue.

here we go https://github.com/element-hq/synapse/pull/17513

**Comment by anoadragon453** [comment]
@AndrewFerr should this PR be closed in favour of https://github.com/element-hq/synapse/pull/17513?

**Comment by AndrewFerr** [comment]
> should this PR be closed in favour of #17513?

Sure. This is technically still a working implementation of an open MSC, but there's not much value in keeping this open alongside a competing PR & MSC.

**Pull request closed without merging**
