### PR TITLE
Corrected the port to 8008 instead of 8443

### PR DESCRIPTION
**Pull request by bruvv**
### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [x] [Code style](https://element-hq.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

### CODE REVIEW

**Comment by anoadragon453** [comment]
@bruvv could you give a bit more detail as to why you need this change? As far as I can see, the docker-compose file is saying that you can either use traefik as a reverse proxy (including to terminate TLS), or have Synapse handle TLS traffic itself directly. Typically `8448` is the port you'd do that on.

**Comment by bruvv** [comment]
Well I use Cloudflare and the Synapse itself is not running on port 8448. So this will never work in trafic or any other reverse proxy either. The beginning of the port doesn't matter you can use what ever but inside the container you need to use 8008

**Comment by devonh** [comment]
This file is only meant to be an example - [as mentioned here](https://github.com/element-hq/synapse/blob/03937a1cae18900350a6d16a2714111a2847c821/contrib/docker/README.md?plain=1#L6-L7), and is intended to be modified by whoever uses it. There are many possible ways to setup networking access to Synapse and it would be unnecessarily burdensome to correctly document them all.

The file shows different configuration options for a small selection of possibilities in order to help people understand some of the configuration options. The docker-compose file is not meant to be used directly without modification.

I think it would be best if we kept the `8448` port in the example.

**Comment by bruvv** [comment]
I think you are missing some knowledge on how docker is working or I am missing some knowledge on how synapse is running. Is anything from synapse running on 8443? If so then yes close it, if it is running on 8008 as all the documentation states then this docker-compose file in the repo is wrong.

**Comment by anoadragon453** [comment]
Synapse will listen on both ports `8448` and `8008` in its default, generated config:

https://github.com/element-hq/synapse/blob/03937a1cae18900350a6d16a2714111a2847c821/synapse/config/server.py#L799-L800

`8448` will have TLS termination enabled, whereas `8008` will not. You *can* expose `8448` directly to the internet and configure Synapse with TLS certificates, such that it can do its own TLS termination. But it's usually recommended to put `8008` behind a reverse proxy instead.

**Pull request closed without merging**
