### PR TITLE
Enable user without password

### PR DESCRIPTION
**Pull request by dklimpel**
Replaces: https://github.com/matrix-org/synapse/pull/16739

Closes: https://github.com/matrix-org/synapse/issues/10397

An administrator should know whether he wants to set a password or not.
There are many uses cases where a blank password is required.

- Use of only some users with SSO.
- Use of bots with password, users with SSO

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [x] Pull request includes a [sign off](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#sign-off)
* [x] [Code style](https://element-hq.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

Signed-off-by: Dirk Klimpel [5740567+dklimpel@users.noreply.github.com](mailto:5740567+dklimpel@users.noreply.github.com)

### CODE REVIEW

**Comment by erikjohnston** [comment]
@dklimpel Sorry that I missed getting this merged before we forked :facepalm:

**Comment by erikjohnston** [comment]
Err, I have no idea why GH is closing this issue?!

**Comment by wrjlewis** [comment]
Have raised a ticket with GH to fix / understand what is happening here..

**Comment by dklimpel** [comment]
Should I create a new PR?

**Pull request closed without merging**
