### PR TITLE
Include knock endpoints in worker federation docs

### PR DESCRIPTION
**Pull request by AndrewFerr**
### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [x] [Code style](https://element-hq.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

### CODE REVIEW

**Comment by clokep** [comment]
Like I mentioned at https://github.com/element-hq/synapse/pull/17058#issuecomment-2085446196 this probably needs to update sytest and complement too.

**Comment by anoadragon453** [comment]
@AndrewFerr FYI I'm waiting for those changes in Sytest and Complement to appear before reviewing this PR.

**Comment by anoadragon453** [comment]
@AndrewFerr and if you're not sure how to do this, you can follow my example: https://github.com/element-hq/synapse/pull/17058#issuecomment-2110749902

**Comment by AndrewFerr** [comment]
Turns out this was always the same as https://github.com/element-hq/synapse/pull/17058 :man_facepalming:  Thanks for getting the Sytest & Complement changes in!

**Pull request closed without merging**
