### PR TITLE
Add missing license header

### PR DESCRIPTION
**Pull request by erikjohnston**
File was added in #17326, cc @AndrewFerr for future reference

### CODE REVIEW

**Comment by AndrewFerr** [comment]
D'oh, I misread [this comment](https://github.com/element-hq/synapse/pull/17326#discussion_r1743745237) as meaning new files didn't need _any_ header, not just the "originally licensed" line.

**Comment by AndrewFerr** [comment]
With that said, do other newly-added files need the license header?  If so, I will add them.

**Comment by erikjohnston** [comment]
> With that said, do other newly-added files need the license header? If so, I will add them.

Yeah, they do! Thanks :slightly_smiling_face:

**Comment by AndrewFerr** [comment]
Opened a new PR, since I don't have access to push more commits to this one: https://github.com/element-hq/synapse/pull/17799

And it turns out that I had missed the relevant comment all along: https://github.com/element-hq/synapse/pull/17326#discussion_r1736844997

**Comment by anoadragon453** [comment]
This PR appears to be superseded by https://github.com/element-hq/synapse/pull/17799.

**Pull request closed without merging**
