### PR TITLE
Filter destination rooms in admin API

### PR DESCRIPTION
**Pull request by MisguidedEmails**
No filtering was done, so all rooms were returned when hitting `/_synapse/admin/v1/federation/destinations/<destination>/rooms`

Fixes: https://github.com/element-hq/synapse/issues/16883

Note: feel free to re-create this, or amend it in any way - I'm not willing to provide a legal name for the CLA

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [x] [Code style](https://element-hq.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://element-hq.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

### CODE REVIEW

**Comment by MisguidedEmails** [comment]
> sorry that this (seems like it) came as an unwelcome surprise when you tried to do so

I knew of the CLA, though I was expecting/hoping that I could say "yeah sure whatever, I don't care, take my stuff", but it seems it's more complex/formal than that. Also to clarify, it's not so much that it's a legal vs common name problem, but more that I'd rather not have any personal information associated with this account. (I understand it's not going to make it publicly visible, but it would be trusting whatever parties I give it to that the data will always be secure. I'd prefer not to have to do that).

**Comment by reivilibre** [comment]
I completely understand your reasoning.

I have checked and I'm afraid the lawyers win this time: I'm afraid I can't take your contribution. Sorry.

**Comment by MisguidedEmails** [comment]
Unfortunate, but I understand. Though what happens with this specific issue? The fix is small, potentially small/trivial enough that it isn't actually copyrightable code. Though if it is indeed code that is copyrighted (against my will, really), then does that mean it _cannot_ be fixed? As I'd imagine someone else would fix it in the same manner, due to it's simplicity (unless of course there is a more elaborate fix that doesn't use the same code).

It's a bit of a bind if there are bug fixes - or I guess features too - down the line that are submitted (by me or otherwise) and that fix is then "claimed" since there is no way for the person to relinquish the copyright to Element without the CLA.

**Comment by wrjlewis** [comment]
Since this is a small and trivial change as you say, we can make an exception and raise this as a PR ourselves. 
Though a small caveat that we can't make guarantees on how soon we can doit, being a time constrained team.

**Pull request closed without merging**
